### ISSUE TITLE
Issue with the .stl files of objects provided in IndustRealkit

### ISSUE THREAD

**Issue by ismarou** [NVlabs/industrealkit#1]
Hello,

As I tried to 3D print some of the objects provided as .stls in the following [link](https://github.com/NVlabs/industrealkit/tree/main/pegs_and_holes/stl), I noticed that these stls do not have any information inside them, besides some standard wireframe.

Am I missing something or is there something wrong with the uploaded data?

Best,
Isidoros

**Comment by ynarang** [comment]
Hi @ismarou,

I just tried downloading `hole_rect_12mm.stl` and opened it in [MeshLab](https://www.meshlab.net/). I see the full 3D geometry. Can you give this a try and let me know if you run into any issues?

Best,
Yash

**Comment by dhruvmetha** [comment]
Hey @ynarang , could you also please provide us with the peg .stl files? I see only socket files in the repository. Thanks!

**Comment by ynarang** [comment]
Hi @dhruvmetha, the `round pegs` are intended to be initially placed within the `round peg trays` and inserted by the robot into the `round holes`. Similarly, the `rectangular pegs` are intended to be initially placed within the `rectangular peg trays` and inserted by the robot into the `rectangular holes`. We don't provide STL files for the `pegs`, as they are metal parts that were purchased. We do provide STL files for the `peg trays` and `holes`, though.
